More git hookery.

diff --git a/common/bin/git-hooks/pre-commit b/common/bin/git-hooks/pre-commit
--- a/common/bin/git-hooks/pre-commit
+++ b/common/bin/git-hooks/pre-commit
@@ -1,4 +1,12 @@
 #!/bin/bash
+# git pre-commit hook wrapper.
+# See `man githooks` for more information on hooks.
+
+changed_files=`git diff --cached --name-only HEAD`
+if [ -z "$files" ] ; then # quick exit when no files changed
+  $DEBUG_HOOKS || echo 'No files in staging area. Exiting pre-commit hook.'
+  exit
+fi
 echo 'Running pre-commit hooks (base script located at .git/hooks/pre-commit)...'
 
 # `pee` comes from the moreutils package. This is nice because it allows us to
@@ -7,16 +15,17 @@ echo 'Running pre-commit hooks (base script located at .git/hooks/pre-commit)...
 hooks_directory='.git/hooks/pre-commit-hooks'
 if [ -e "$hooks_directory" ] ; then
   if [ "$(ls -A $hooks_directory)" ] ; then
+    # run the hooks
     pee $hooks_directory/*
+
+    # if any of the scripts exited with failure error code
+    if [[ $? != 0 ]] ; then
+      echo "COMMIT REJECTED!"
+      exit 1
+    fi
   else
     echo "[WARN] No hooks present in directory: $hooks_directory."
   fi
 else
   echo "[WARN] No hook directory present: $hooks_directory."
-fi
-
-# if any of the scripts exited with failure error code
-if [[ $? != 0 ]] ; then
-  echo "COMMIT REJECTED!"
-  exit 1
 fi
diff --git a/common/bin/git-hooks/pre-commit-hooks/no-git-merge-issues b/common/bin/git-hooks/pre-commit-hooks/no-git-merge-issues
--- a/common/bin/git-hooks/pre-commit-hooks/no-git-merge-issues
+++ b/common/bin/git-hooks/pre-commit-hooks/no-git-merge-issues
@@ -5,9 +5,11 @@ ERRORS='(<<<<<<<|>>>>>>>)'
 
 $DEBUG_HOOKS || echo 'Checking for git merge conflict markers...'
 
-git diff --cached --name-only HEAD | \
-  GREP_COLOR='4;5;37;41' xargs grep --color --with-filename -n -E $ERRORS &&
-  echo '[ERROR] Found at least one git merge conflict marker. Exiting!' &&
-  exit 1
+files=`git diff --cached --name-only HEAD`
+if [ -e "$files" ] ; then
+  GREP_COLOR='4;5;37;41' grep --color --with-filename -n $FORBIDDEN $files &&
+    echo '[ERROR] Found at least one git merge conflict marker. Exiting!' &&
+    exit 1
+fi
 
 $DEBUG_HOOKS || echo 'No git merge conflicts.'
